name: uno
recipe: laravel
config:
  webroot: public
  php: "8.4"

services:
  appserver:
    build_as_root:
      - apt-get update -y && pecl install pcov && docker-php-ext-enable pcov
      - curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
      - apt-get install -y nodejs
    build:
      - composer i
      - npm install
    ports:
      - 3009:3009
  database:
    portforward: 3307

tooling:
  npm:
    service: appserver
  node:
    service: appserver
  php:
    service: appserver
